# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: setup gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: get commit info
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          {
            echo 'commit_msg<<EOF'
            git log -1 --pretty=%B
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: create commit release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ steps.vars.outputs.sha_short }}
          name: Build ${{ steps.vars.outputs.sha_short }}
          body: |
            ## Changelog
            ${{ steps.vars.outputs.commit_msg }}

            Commit: ${{ github.sha }}
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: delete old latest release
        run: |
          gh release delete latest --yes --cleanup-tag || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create latest release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build (${{ steps.vars.outputs.sha_short }})
          body: |
            ## Changelog
            ${{ steps.vars.outputs.commit_msg }}
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}